routes:
 # A route named bacon
 bacon: { model: bacon, view: bacon }
 dualmodel: { model: [ single, double ], view: single }
 dualview:
  model: single
  view: [single,double] 
 admin:
  model: admin
  view: admin	
 # All of my API resources can go here
 api:
  costs:
   model: [admin, robo]
   view: admin	
  packages:
   model: admin
   view: admin	
